---
- name: Upgrade Debian-based systems
  ansible.builtin.apt:
    name: "*"
    only_upgrade: true
    update_cache: true
  when: ansible_facts['os_family'] in ["Debian", "Ubuntu"]

- name: Upgrade RedHat-based systems
  ansible.builtin.dnf:
    name: "*"
    update_only: true
    update_cache: true
  when: ansible_facts['os_family'] in ["RedHat", "Rocky"]
