Vagrant.configure("2") do |config|

  vm_configs = [
    { name: "0-debian", box: "generic/debian12", version: "4.3.12" },
    { name: "0-ubuntu", box: "bento/ubuntu-24.04", version: "202502.21.0" },
    { name: "0-rocky", box: "bento/rockylinux-9", version: "202502.21.0" }
  ]

  def configure_virtualbox(machine, memory, cpus)
    machine.vm.provider "virtualbox" do |vb|
      vb.name   = machine.vm.hostname
      vb.memory = memory
      vb.cpus   = cpus
      vb.gui    = false
    end
  end

  vm_configs.each do |vm|
    config.vm.define vm[:name] do |node|
      node.vm.box = vm[:box]
      node.vm.box_version = vm[:version]
      node.vm.hostname = vm[:name]

      node.vm.provision "ansible" do |ansible|
        ansible.playbook = "../ansible/bases/playbook.yml"
      end

      configure_virtualbox(node, "2048", 2)
    end
  end
end
