---
- hosts: all
  become: true
  tasks:
    - name: Update dnf cache
      dnf:
        update_cache: yes
        state: latest
      when: target_os == "rocky"

    - name: Get /etc/machine-id file from VM
      fetch:
        src: /etc/machine-id
        dest: "./machine_ids/{{ inventory_hostname }}_machine-id"
        flat: yes

    - name: Delete /etc/machine-id file (if exists)
      file:
        path: /etc/machine-id
        state: absent

    - name: Recreate /etc/machine-id file
      file:
        path: /etc/machine-id
        state: touch
        mode: '0644'

    - name: Delete persistent net rules file
      file:
        path: /etc/udev/rules.d/70-persistent-net.rules
        state: absent

    - name: Shutdown the machine
      command: /sbin/shutdown -h now
      async: 0
      poll: 0
      ignore_errors: true
      failed_when: false

    - name: Wait for machine to shut down (SSH port closed)
      delegate_to: localhost
      wait_for:
        host: "{{ ansible_ssh_host | default(inventory_hostname) }}"
        port: 22
        state: stopped
        timeout: 120
