---
- hosts: all
  become: true
  tasks:
    - name: Modify /etc/apt/sources.list file
      ansible.builtin.replace:
        path: /etc/apt/sources.list.d/ubuntu.sources
        regexp: 'http://'
        replace: 'https://'
        backup: yes

    - name: Update apt cache
      apt:
        update_cache: yes
        upgrade: yes
      when: target_os == "ubuntu"

    - name: Get /etc/machine-id file from VM
      fetch:
        src: /etc/machine-id
        dest: "./machine_ids/{{ inventory_hostname }}_machine-id"
        flat: yes

    - name: Delete /etc/machine-id file (if exists)
      file:
        path: /etc/machine-id
        state: absent

    - name: Delete /var/lib/dbus/machine-id file (if exists)
      file:
        path: /var/lib/dbus/machine-id
        state: absent

    - name: Recreate /etc/machine-id file
      file:
        path: /etc/machine-id
        state: touch
        mode: '0644'
