---
- hosts: all
  become: true
  tasks:
    - name: Find all .repo files in /etc/yum.repos.d/
      ansible.builtin.find:
        paths: /etc/yum.repos.d/
        patterns: "*.repo"
      register: repo_files

    - name: Replace 'http://' by 'https://' in all .repo files
      ansible.builtin.replace:
        path: "{{ item.path }}"
        regexp: 'http://'
        replace: 'https://'
        backup: yes
      loop: "{{ repo_files.files }}"

    - name: Update dnf cache
      dnf:
        update_cache: yes
        state: latest
      when: target_os == "rocky"

    - name: Get /etc/machine-id file from VM
      fetch:
        src: /etc/machine-id
        dest: "./machine_ids/{{ inventory_hostname }}_machine-id"
        flat: yes

    - name: Delete /etc/machine-id file (if exists)
      file:
        path: /etc/machine-id
        state: absent

    - name: Recreate /etc/machine-id file
      file:
        path: /etc/machine-id
        state: touch
        mode: '0644'

    - name: Create user tux with password rootroot
      user:
        name: tux
        password: "{{ 'rootroot' | password_hash('sha512') }}"
        shell: /bin/bash
        state: present

    - name: Allow user tux to sudo without password
      copy:
        dest: /etc/sudoers.d/tux
        content: "tux ALL=(ALL) NOPASSWD: ALL\n"
        owner: root
        group: root
        mode: '0440'

    - name: Configure keyboard layout
      ansible.builtin.command: localectl set-keymap be

    - name: Configure timezone to Europe/Brussels
      ansible.builtin.command: timedatectl set-timezone Europe/Brussels

