---
- name: Ensure sshpass is installed on control machine
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Install sshpass if not present
      ansible.builtin.apt:
        name: sshpass
        state: present

- name: Configure static IP on target
  hosts: target
  gather_facts: false
  become: true
  tasks:
    - name: Replace DHCP config with static config via raw
      ansible.builtin.raw: |
        sed -i '/iface {{ interface_name }} inet dhcp/,+3d' /etc/network/interfaces
        echo "auto {{ interface_name }}" >> /etc/network/interfaces
        echo "iface {{ interface_name }} inet static" >> /etc/network/interfaces
        echo "    address {{ ip_address }}" >> /etc/network/interfaces
        echo "    netmask {{ netmask }}" >> /etc/network/interfaces
        echo "    gateway {{ gateway }}" >> /etc/network/interfaces
        echo "    dns-nameservers {{ dns1 }} {{ dns2 }}" >> /etc/network/interfaces
      changed_when: true
...
