---
- name: Install necessary packages for Debian
  ansible.builtin.apt:
    name:
      - firewalld
      - python3-firewall
      - htop
      - wget
      - curl
      - bash-completion
      - nano
      - tar
    state: present
    update_cache: true
